- tp_timesheet/docker_handler.py
Add a while loop to check whether docker container is running to prevent RemoteDisconnected error
> Add time buffer to allow docker to run

- setup.py
- tp_timesheet/__main__.py
- tp_timesheet/dates.py
It's a bit troublesome but there's a new module required for this. @ThorpeJosh would you want to add it to the docker?
> update: exclude public holidays from submission dates

- README.md
- tp_timesheet/__main__.py
- tp_timesheet/submit_form.py
@siewyeng @lamchuntat 
This should make development easier as we can add this cli flag `--dry-run` or `-d` when testing.
Note I changed `--debug` to `--verbose` to better distinguish it from `--dry-run`
> feat: dry-run mode for easier debugging/testing

- tp_timesheet/__main__.py
@siewyeng  @ThorpeJosh  @lamchuntat 
Related to : #7
> new feat:adding notification feature

- README.md
- tp_timesheet/__main__.py
- tp_timesheet/config.py
@ siewyeng @lamchuntat @ changukshin
> feat: use config file instead of env vars

- tp_timesheet/__main__.py
> update:remove userWarning if not verbose

- Jenkinsfile
Removes lingering build files on jenkins agent
> cicd: cleanup successful jenkins builds

- setup.py
> fix: pylint.rc compatibility with old versions

- tp_timesheet/__main__.py
- tp_timesheet/config.py
- tp_timesheet/date_utils.py
- write one function to do sanity check (date_utils.check_date)
- add one option to config (max_submit_within_days)
- logics for version compatibility
- unfamilliar with this implementation. may need to be modified.
> sanity check date prior to submission

- tp_timesheet/__main__.py
- tp_timesheet/config.py
- tp_timesheet/date_utils.py
Reverts ThorpeJosh/tp-timesheet#37
> Revert "sanity check date prior to submission"

- tp_timesheet/__main__.py
- tp_timesheet/config.py
PR addressing #31 and #32. This will definitely cause conflicts with #24 though. I will resolve them if #24 gets merged first.
> fix: cls print format and consistency of verbose arg

- tp_timesheet/__init__.py
- tp_timesheet/__main__.py
- tp_timesheet/config.py
- tp_timesheet/schedule.py
- tp_timesheet/submit_form.py
@ThorpeJosh @siewyeng @changukshin 
Need some advice for this PR. The logger that I added to `__main__.py` cannot be used in other modules, ie. only log messages from `__main__.py` are recorded, log messages from other modules couldn't be seen in stdout nor the log file :/
> Add logger

- tp_timesheet/config.py
> add 'r' for regex string

- tp_timesheet/__main__.py
> Added a text indicating dry_run to notification message

- tp_timesheet/__main__.py
- tp_timesheet/date_utils.py
- tp_timesheet/tests/test_weekend_public_holiday.py
Rename "date_fn".
Check whether selected dates only include weekends, don't launch Docker if that is the case.
> perf: skip docker instantiation if selected dates fall on weekends only

- tp_timesheet/submit_form.py
This is meant to be a quick fix for https://github.com/ThorpeJosh/tp-timesheet/issues/49
Xpaths for different fields in the form have been updated in submit_form. I will continue to work on a more robust way to address this issue.
> fix: update xpath in submit_form

- tp_timesheet/submit_form.py
Updated how the different fields in the forms are being located
> fix: change submit_form element locator

- Jenkinsfile
- tp_timesheet/__init__.py
Support latest python 3.11 now that is is released. And increment version number.
> Upgrade python version

- tp_timesheet/__main__.py
- tp_timesheet/date_utils.py
- tp_timesheet/tests/test_weekend_public_holiday.py
This PR has two additions:
- Adds the ability to choose the working hours with the `--hours 4` flag. Defaults to 8
- Adds support for `--start yesterday`
> Half day support

- tp_timesheet/__main__.py
- tp_timesheet/docker_handler.py
This addresses #58 
It will check brew and docker are installed. If docker is missing it will try to download with brew.
It also checks the docker engine is running and waits for it to launch if not (common problem encountered).
> feature: auto install and launch docker

- tp_timesheet/__init__.py
- tp_timesheet/config.py
- tp_timesheet/tests/test_config.py
> 65 add api key to config

- tp_timesheet/__main__.py
> feat: support for --version cli option

- tp_timesheet/clockify_timesheet.py
Reverts ThorpeJosh/tp-timesheet#73
> Revert "workspace id formatting + reformatting"

- tp_timesheet/__main__.py
- tp_timesheet/clockify_timesheet.py
addresses #84. Yet to update `tp-timesheet --help` and timesheet form
> feat:add project and task name args

- Jenkinsfile
- tp_timesheet/config.py
- tp_timesheet/tests/test_clockify_ids.py
- tp_timesheet/tests/test_config.py
- tp_timesheet/tests/test_date_utils.py
warning: the Jenkins environment portion has not been tested
> Addition of clockify API check

- Jenkinsfile
- tp_timesheet/tests/test_clockify.py
@siewyeng I have written a quick test to check tags are working as expected. All passing locally with it based on your PR.
Let me know if this test is sufficient for the scope of your PR and merge it if you are happy.
> cicd: unit test for clockify tags

- .pylintrc
- setup.py
- tp_timesheet/clockify_timesheet.py
- tp_timesheet/tests/test_clockify.py
> fix:project name and project ids and task ids in test_clockify

- tp_timesheet/__init__.py
This tag includes below PRs,
- https://github.com/ThorpeJosh/tp-timesheet/pull/111
> cicd:v2.1.1
